<?php

/**
 * SiteTermTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteTermTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteTermTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteTerm');
    }
}