homeSuccess:
  layout: layoutA

smtHomeSuccess:
  layout: smtLayoutGroup

smtEditSuccess:
  layout: smtLayoutGroup

smtMemberListSuccess:
  layout: smtLayoutGroup

smtJoinlistSuccess:
  layout: smtLayoutMember

smtJoinInput:
  layout: smtLayoutGroup

smtJoinError:
  layout: smtLayoutSite

smtQuitSuccess:
  layout: smtLayoutGroup

smtQuitError:
  layout: smtLayoutSite

smtSearchSuccess:
  layout: smtLayoutSite
